version: "3"

services:
  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jeewonuser
      POSTGRES_PASSWORD: jeewonpassword
      POSTGRES_DB: jeewondatabase
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "jeewonuser", "-d", "jeewondatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wisconsin-generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]

networks:
  default:
    name: jw-network