channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=22.1.2
- pip:
  - mlflow
  - cloudpickle==1.2.2
  - dataclasses==0.6
  - lz4==3.1.3
  - psutil==5.9.0
  - scikit-learn==1.1.3
  - typing-extensions==4.4.0
name: mlflow-env
